name: odatsapereen_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.4+5

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:

    - assets/icon.png   # صورة الأيقونة الأساسية

# إعدادات توليد أيقونة التطبيق تلقائيًا
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
