name: odatsapereen_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.6+7

environment:
  sdk: ^3.10.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  syncfusion_flutter_pdfviewer: ^32.1.23
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:

    - assets/icon.png # صورة الأيقونة الأساسية
    - assets/book.pdf
# إعدادات توليد أيقونة التطبيق تلقائيًا
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
